- name: BACKUP |  Dump do Último Backup
  postgresql_db:
    name: "{{ item }}"
    state: dump
    target: /tmp/{{ item }}.sql
  with_items:
    - bdw3erp1
    - bd1
  when: ansible_distribution == "Alpine" 

#- name: BACKUP | Tranferindo backup do labalpine1 para o labcentos
#  synchronize: src=/tmp/{{ item }}.sql dest=/tmp{{ item }}
#  delegate_to: labalpine1
#  with_items:
#      - bdw3erp1
#      - bd1
#  when: ansible_distribution == "CentOS"

- name: BACKUP | Transferindo backup do labalpine para o master
  ansible.builtin.fetch:
    src:  /tmp/{{ item }}.sql
    dest:  /tmp/

  with_items:
    - bdw3erp1
    - bd1
  when: ansible_distribution == "Alpine" 

   
- name: BACKUP | Transferindo backup do master para o labcentos
  ansible.builtin.copy:
    src:  /tmp/labalpine1/tmp/{{ item }}.sql
    dest:  /tmp/
  with_items:
    - bdw3erp1
    - bd1
  when: ansible_distribution == "CentOS"

- name: BACKUP | Criando DB no labcentos
  postgresql_db:
    name: "{{ item }}"
  with_items:
    - bdteste01
    - bdteste02
  when: ansible_distribution == "CentOS"


- name: BACKUP | Restore dump
  postgresql_db: 
    name: "{{ item.dst }}"
    state: restore
    target: /tmp/{{ item.src }}.sql
  with_items:
    - { dst: bdteste01, src: bdw3erp1 }
    - { dst: bdteste02, src: bd1 }
  when: ansible_distribution == "CentOS"



#  paramêtros iniciais:
#        servidor de origem
#            Obrigatório
#            Tipo: Combo
#            Valores possíveis: bdw3erp1, bd1
#        servidor de destino
#            Obrigatório
#            Tipo: Combo
#            Valores possíveis: bdteste01, bdteste02
#        nome do banco de dados a ser copiado
#            Obrigatório
#            Tipo: Texto
#        nome do banco de dados a ser criado
#            Opcional (Caso não tenha assumir o mesmo valor do campo "nome do banco de dados a ser copiado"
#            Tipo: Texto
