---

- name: RPM | Update  
  yum:  
    name: '*' 
    state: latest 

- name: RPM | Desabilitando SELinux no CentOS
  lineinfile:
    dest=/etc/selinux/config
    state=present
    regexp={{ item.regexp }}
    line={{ item.line }}
    backrefs=yes
  with_items:
  - { regexp: 'SELINUX=enforcing', line: 'SELINUX=permissive' }
  when: ansible_distribution == "CentOS"

      
- name: RPM | Instala o epel-release 
  yum: 
    name: epel-release

- name: RPM | Instalando pacotes common
  yum:  
    name: "{{ common_packages_rpm }}"
    state: latest 
- name: RPM | Desativando ipv6
  sysctl: name=net.ipv6.conf.{{ansible_default_ipv4.interface}}.disable_ipv6 value=1 state=present reload=yes sysctl_set=yes
  with_items:
    - { nome: net.ipv6.conf.all.disable_ipv6, value: 1 }
    - { nome: net.ipv6.conf.default.disable_ipv6, value: 1 }
   
- name: RPM | Reconfigurando swap de 60 para 10
  sysctl: name=vm.swappiness value=10 state=present reload=yes sysctl_set=yes

...
