common_packages_debian:
  - aspell-pt-br
  - bash-completion
  - bc
  - bzip2
  - curl
  - dnsutils
  - dbus
  - fping
  - git
  - htop
  - less
  - lsb-release
  - net-tools
  - nmap
  - ntpdate
  - psmisc
  - screen
  - sudo
  - tree
  - unzip
  - vim
  - wget
  - xz-utils
  - zip

common_packages_rpm:
  - bash-completion
  - bc
  - bzip2
  - curl
  - dbus
  - fping
  - git
  - htop
  - less
  - net-tools
  - nmap
  - psmisc
  - screen
  - sudo
  - tree
  - unzip
  - vim
  - wget
  - zip

 

  
